SCRIPTS_DIR=__SCRIPTS_DIR__ #/share/apps/bin
CIRCOS_BIN=__CIRCOS_DIR__ #/share/apps/circos-0.60/bin/circos

BAM_PREFIXES=__BAM_PREFIXES__
OUT_DIRS=__OUT_DIRS__
IDS=__IDS__
GENDERS=__GENDERS__

COND=__COND__
BED=__BED__
GFF=__GFF__

EXPR_DIR=__EXPR_DIR__
CIRCOS_OUT_DIR=__CIRCOS_OUT_DIR__

NUM_GROUPS=__NUM_GROUPS__
